# File aliases
if [[ -x "$HOME/.local/opt/vim-9.2/bin/vim" ]]; then
    alias vim='"$HOME/.local/opt/vim-9.2/bin/vim"'
    alias ezvim='"$HOME/.local/opt/vim-9.2/bin/vim" -Nu "${XDG_CONFIG_HOME:-$HOME/.config}/vim/ezvimrc"'
    if [[ -n "${WSL_DISTRO_NAME:-}" ]]; then
        alias ezgvim='GSK_RENDERER=cairo "$HOME/.local/opt/vim-9.2/bin/gvim" -f -Nu "${XDG_CONFIG_HOME:-$HOME/.config}/vim/ezvimrc"'
    else
        alias ezgvim='"$HOME/.local/opt/vim-9.2/bin/gvim" -f -Nu "${XDG_CONFIG_HOME:-$HOME/.config}/vim/ezvimrc"'
    fi
else
    if [[ -x /usr/bin/vim ]]; then
        alias vim='/usr/bin/vim -Nu "${XDG_CONFIG_HOME:-$HOME/.config}/vim/vimrc"'
        alias ezvim='/usr/bin/vim -Nu "${XDG_CONFIG_HOME:-$HOME/.config}/vim/ezvimrc"'
    else
        alias ezvim='vim -Nu "${XDG_CONFIG_HOME:-$HOME/.config}/vim/ezvimrc"'
    fi
fi

if ls --color=auto -d . >/dev/null 2>&1; then
    alias ls="ls --color=auto"
fi

alias ll="ls -l"
alias la="ls -a"
alias lal="ls -al"

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

_rgrep_files() {
    local extension="$1"
    shift

    if (( $# == 0 )); then
        echo "Usage: ${FUNCNAME[1]} <grep-args>" >&2
        return 1
    fi

    find . -name "*.${extension}" -exec grep "$@" {} +
}

rgreph() {
    _rgrep_files h "$@"
}

rgrephl() {
    _rgrep_files h -l "$@"
}

rgrepc() {
    _rgrep_files c "$@"
}

rgrepcl() {
    _rgrep_files c -l "$@"
}

if [[ "$(uname)" == "Darwin" ]]; then
    alias pfd='osascript -e '\''tell application "Finder" to return POSIX path of (insertion location as alias)'\'''
    alias cdf='cd "$(pfd)"'
    alias ofd="open ."

    alias afk='osascript -e "tell application \"System Events\" to keystroke \"q\" using {control down, command down}"'
    alias slp='osascript -e "tell application \"System Events\" to sleep"'
    alias sdn='osascript -e "tell application \"System Events\" to shut down"'
    alias rst='osascript -e "tell application \"System Events\" to restart"'
    alias spmac='osascript -e "tell application \"System Events\" to sleep"'
    alias sdmac='osascript -e "tell application \"System Events\" to shut down"'
    alias rsmac='osascript -e "tell application \"System Events\" to restart"'
fi

alias ff="fastfetch"
